# Site settings
title:
email:
description: > # this means to ignore newlines until "baseurl:"
  SooLash Studio specializes in eyelash extensions and semi-permanent tattoos. We are located in Annandale, Virginia.
  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# User setting
owner: SooLash Studio
email: soolashstudio@gmail.com
facebook_username:
twitter_username:
github_username:
address:
  - line: 7310 McWhorter Pl #D
  - line: Annandale, Virginia 22003
  # Feel free to add more lines here 
telephone: 202-997-4494
copyright:

# API settings
google_api_key: AIzaSyBE5el4WZDP4HD-qfUfotmVARjSQ01KXQo

# Build settings
markdown: kramdown
